project:
  type: website
  output-dir: _site

website:
  title: "Comparing Raw Survival Data to Exponential Models"
  navbar:
    left:
      - href: index.qmd
        text: Home

format:
  html:
    toc: true